spring.application.name=newbot
server.port=8085

spring.ai.openai.api-key=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

spring.ai.openai.base-url=https://openrouter.ai/api

spring.ai.openai.chat.options.model=meta-llama/llama-3.1-8b-instruct

spring.ai.openai.embedding.options.model=text-embedding-3-small


spring.ai.openai.chat.options.temperature=0.2

app.pdf-folder=pdf

spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.username=postgres
spring.datasource.password=32494832
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB